<?php
session_start();
if (!isset($_SESSION['user'])) {
    header("Location: login.php");
    exit();
}

// Check if user has permission to send emails (admin and teacher only)
if (!in_array($_SESSION['user_role'] ?? 'staff', ['admin', 'teacher'])) {
    echo "<script>alert('Access denied. You do not have permission to send emails.'); window.location.href='dashboard.php';</script>";
    exit();
}

require 'vendor/autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

include 'db_connect.php';

// Handle form submission
if ($_POST && isset($_POST['send_email'])) {
    $selected_date = $_POST['report_date'];
    
    $sql = "SELECT name, department, status, timestamp FROM attendance WHERE DATE(timestamp) = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("s", $selected_date);
    $stmt->execute();
    $result = $stmt->get_result();
    
    if ($result->num_rows == 0) {
        echo "<script>alert('No attendance records found for " . date('F d, Y', strtotime($selected_date)) . "');</script>";
    } else {
        $body = "
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f8f9fa; }
                .container { max-width: 800px; margin: 0 auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
                .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }
                .header h1 { margin: 0; font-size: 24px; }
                .header p { margin: 5px 0 0 0; opacity: 0.9; }
                .content { padding: 30px; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th { background: #4a5568; color: white; padding: 12px; text-align: left; }
                td { padding: 12px; border-bottom: 1px solid #e2e8f0; }
                tr:nth-child(even) { background: #f7fafc; }
                .status-in { color: #22543d; font-weight: bold; }
                .status-out { color: #742a2a; font-weight: bold; }
                .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #718096; font-size: 14px; }
            </style>
        </head>
        <body>
            <div class='container'>
                <div class='header'>
                    <h1>📊 Attendance Report</h1>
                    <p>" . date('F d, Y', strtotime($selected_date)) . "</p>
                    <p>Generated by: " . htmlspecialchars($_SESSION['user']) . " (" . ucfirst($_SESSION['user_role'] ?? 'User') . ")</p>
                </div>
                <div class='content'>
                    <table>
                        <tr><th>Name</th><th>Department</th><th>Status</th><th>Time</th></tr>";

        while ($row = $result->fetch_assoc()) {
            $statusClass = strtolower($row['status']) == 'in' ? 'status-in' : 'status-out';
            $body .= "<tr>
                <td>{$row['name']}</td>
                <td>{$row['department']}</td>
                <td class='{$statusClass}'>{$row['status']}</td>
                <td>" . date('h:i A', strtotime($row['timestamp'])) . "</td>
            </tr>";
        }
        $body .= "</table>
                </div>
                <div class='footer'>
                    <p>Generated automatically by Attendance Management System</p>
                </div>
            </div>
        </body>
        </html>";

        $mail = new PHPMailer(true);
        try {
            $mail->isSMTP();
            $mail->Host = 'smtp.gmail.com';
            $mail->SMTPAuth = true;
            $mail->Username = 'spandyparikh@gmail.com';
            $mail->Password = 'keiy dyqj ozqy hqgi';
            $mail->SMTPSecure = 'tls';
            $mail->Port = 587;

            $mail->setFrom('spandyparikh@gmail.com', 'Attendance System');
            $mail->addAddress($_POST['email_address']);

            $mail->isHTML(true);
            $mail->Subject = 'Attendance Report - ' . date('F d, Y', strtotime($selected_date));
            $mail->Body = $body;

            $mail->send();
            echo '<div style="background: #d4edda; color: #155724; padding: 15px; border-radius: 8px; margin: 20px; text-align: center; font-weight: bold;">📧 Attendance report sent successfully!</div>';
        } catch (Exception $e) {
            echo '<div style="background: #f8d7da; color: #721c24; padding: 15px; border-radius: 8px; margin: 20px; text-align: center; font-weight: bold;">❌ Mail failed. Error: ' . $mail->ErrorInfo . '</div>';
        }
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Send Email Report - I.R.I.S</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            color: #333;
        }
        
        .sidebar {
            position: fixed;
            left: 0;
            top: 0;
            width: 280px;
            height: 100vh;
            background: rgba(255,255,255,0.95);
            backdrop-filter: blur(20px);
            padding: 30px 0;
            box-shadow: 5px 0 20px rgba(0,0,0,0.1);
            z-index: 1000;
            transition: transform 0.3s ease;
        }
        
        .logo {
            text-align: center;
            padding: 0 30px 30px;
            border-bottom: 1px solid rgba(0,0,0,0.1);
            margin-bottom: 30px;
        }
        
        .logo h1 {
            font-size: 2rem;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            -webkit-background-clip: text;
            background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 5px;
        }
        
        .logo p {
            color: #666;
            font-size: 0.9rem;
        }
        
        .nav-menu {
            list-style: none;
            padding: 0 20px;
        }
        
        .nav-item {
            margin-bottom: 10px;
        }
        
        .nav-link {
            display: flex;
            align-items: center;
            padding: 15px 20px;
            color: #555;
            text-decoration: none;
            border-radius: 15px;
            transition: all 0.3s ease;
            font-weight: 500;
        }
        
        .nav-link:hover, .nav-link.active {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            transform: translateX(5px);
        }
        
        .nav-link i {
            margin-right: 12px;
            width: 20px;
            min-width: 20px;
        }
        
        .main-content {
            margin-left: 280px;
            padding: 30px;
        }
        
        .header {
            background: rgba(255,255,255,0.95);
            backdrop-filter: blur(20px);
            padding: 25px 30px;
            border-radius: 20px;
            margin-bottom: 30px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .header-title h2 {
            color: #333;
            font-size: 2rem;
            margin-bottom: 5px;
        }
        
        .header-title p {
            color: #666;
        }
        
        .user-info {
            display: flex;
            align-items: center;
            gap: 15px;
        }
        
        .user-avatar {
            width: 50px;
            height: 50px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: bold;
            font-size: 1.2rem;
        }
        
        .logout-btn {
            background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%);
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
            font-weight: 500;
            transition: all 0.3s ease;
            text-decoration: none;
        }
        
        .logout-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(255,107,107,0.4);
        }
        
        .card {
            background: rgba(255,255,255,0.95);
            backdrop-filter: blur(20px);
            border-radius: 20px;
            padding: 30px;
            margin-bottom: 30px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
            border: 1px solid rgba(255,255,255,0.3);
        }
        
        .form-group {
            margin-bottom: 20px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #555;
        }
        
        .form-control {
            width: 100%;
            padding: 12px 16px;
            border: 2px solid #e2e8f0;
            border-radius: 12px;
            font-size: 1rem;
            transition: all 0.3s ease;
            background: white;
        }
        
        .form-control:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 3px rgba(102,126,234,0.1);
        }
        
        .btn {
            padding: 12px 24px;
            border: none;
            border-radius: 12px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s ease;
            display: inline-flex;
            align-items: center;
            gap: 8px;
            text-decoration: none;
        }
        
        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 25px rgba(102,126,234,0.3);
        }
        
        .btn-secondary {
            background: linear-gradient(135deg, #48bb78 0%, #38a169 100%);
            color: white;
        }
        
        .btn-secondary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 25px rgba(72,187,120,0.3);
        }
        
        .row {
            display: flex;
            gap: 20px;
            margin-bottom: 20px;
        }
        
        .col-md-6 {
            flex: 1;
        }
    </style>
</head>
<body>
    <div class="sidebar">
        <div class="logo">
            <h1>I.R.I.S</h1>
            <p>Dashboard</p>
        </div>
        
        <ul class="nav-menu">
            <li class="nav-item">
                <a href="dashboard.php" class="nav-link">
                    <i class="fas fa-chart-line"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="add_student.php" class="nav-link">
                    <i class="fas fa-users"></i>
                    <span>Students</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="attendance.php" class="nav-link">
                    <i class="fas fa-calendar-check"></i>
                    <span>Attendance</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="reports.php" class="nav-link">
                    <i class="fas fa-chart-pie"></i>
                    <span>Reports</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="library.php" class="nav-link">
                    <i class="fas fa-book"></i>
                    <span>Library</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="settings.php" class="nav-link">
                    <i class="fas fa-cog"></i>
                    <span>Settings</span>
                </a>
            </li>
            <?php if (isset($_SESSION['user_role']) && $_SESSION['user_role'] == 'admin'): ?>
            <li class="nav-item">
                <a href="manage_users.php" class="nav-link">
                    <i class="fas fa-users-cog"></i>
                    <span>Manage Users</span>
                </a>
            </li>
            <?php endif; ?>
        </ul>
    </div>
    
    <div class="main-content">
        <div class="header">
            <div class="header-title">
                <h2>📧 Send Email Report</h2>
                <p>Select a date and email address to send the attendance report</p>
            </div>
            <div class="user-info">
                <div class="user-avatar">
                    <?= strtoupper(substr($_SESSION['user'], 0, 1)) ?>
                </div>
                <a href="logout.php" class="logout-btn">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
        </div>
        
        <div class="card">
            <form method="POST">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="report_date">📅 Report Date</label>
                            <input type="date" name="report_date" class="form-control" value="<?= date('Y-m-d') ?>" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="email_address">📧 Email Address</label>
                            <input type="email" name="email_address" class="form-control" value="spandyparikh2206@gmail.com" required>
                        </div>
                    </div>
                </div>
                
                <div style="display: flex; gap: 15px;">
                    <button type="submit" name="send_email" class="btn btn-primary">
                        <i class="fas fa-paper-plane"></i> Send Report
                    </button>
                    <a href="dashboard.php" class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i> Back to Dashboard
                    </a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>