<?php
session_start();
if (!isset($_SESSION['user'])) {
    header("Location: login.php");
    exit();
}

require 'vendor/autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

include 'db_connect.php';

if ($_POST && isset($_POST['send_email'])) {
    $selected_date = $_POST['report_date'];

    $sql = "SELECT name, department, status, timestamp FROM attendance WHERE DATE(timestamp) = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("s", $selected_date);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($result->num_rows == 0) {
        echo "<script>alert('No attendance records found for " . date('F d, Y', strtotime($selected_date)) . "');</script>";
    } else {
        $body = buildEmailBody($result, $selected_date);

        $mail = new PHPMailer(true);
        try {
            $mail->isSMTP();
            $mail->Host = getenv('SMTP_HOST') ?: 'smtp.gmail.com';
            $mail->SMTPAuth = true;
            $mail->Username = getenv('SMTP_USER');
            $mail->Password = getenv('SMTP_PASS');
            $mail->SMTPSecure = 'tls';
            $mail->Port = 587;

            $mail->setFrom(getenv('SMTP_USER'), 'Attendance System');
            $mail->addAddress($_POST['email_address']);

            $mail->isHTML(true);
            $mail->Subject = 'Attendance Report - ' . date('F d, Y', strtotime($selected_date));
            $mail->Body = $body;

            $mail->send();
            echo '<div style="background: #d4edda; color: #155724; padding: 15px; border-radius: 8px; margin: 20px; text-align: center; font-weight: bold;">Email sent successfully!</div>';
        } catch (Exception $e) {
            echo '<div style="background: #f8d7da; color: #721c24; padding: 15px; border-radius: 8px; margin: 20px; text-align: center; font-weight: bold;">Mail failed. Error: ' . $mail->ErrorInfo . '</div>';
        }
    }
}

function buildEmailBody($result, $selected_date) {
    $body = "<html><head><style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f8f9fa; }
        .container { max-width: 800px; margin: 0 auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; }
        .header p { margin: 5px 0 0 0; opacity: 0.9; }
        .content { padding: 30px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background: #4a5568; color: white; padding: 12px; text-align: center; }
        td { padding: 12px; border-bottom: 1px solid #e2e8f0; text-align: center; }
        tr:nth-child(even) { background: #f7fafc; }
        .status-in { color: #22543d; font-weight: bold; }
        .status-out { color: #742a2a; font-weight: bold; }
        .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #718096; font-size: 14px; }
    </style></head><body>
    <div class='container'>
        <div class='header'>
            <h1>Attendance Report</h1>
            <p>" . date('F d, Y', strtotime($selected_date)) . "</p>
            <p>Generated by: " . htmlspecialchars($_SESSION['user']) . " (" . ucfirst($_SESSION['user_role'] ?? 'User') . ")</p>
        </div>
        <div class='content'>
            <table>
                <tr><th>Name</th><th>Department</th><th>Status</th><th>Time</th></tr>";

    while ($row = $result->fetch_assoc()) {
        $statusClass = strtolower($row['status']) == 'in' ? 'status-in' : 'status-out';
        $body .= "<tr>
            <td>{$row['name']}</td>
            <td>{$row['department']}</td>
            <td class='{$statusClass}'>{$row['status']}</td>
            <td>" . date('h:i A', strtotime($row['timestamp'])) . "</td>
        </tr>";
    }
    $body .= "</table></div>
    <div class='footer'>
        <p>Generated automatically by Attendance Management System</p>
    </div></div></body></html>";

    return $body;
}
?>
<!-- HTML form omitted for brevity - copy from original send_email.php -->